language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t genzan/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true genzan/docker-react npm run test